name: Build and Deploy to Azure Linux VM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Set up Node.js 20'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login to Docker Hub'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build Docker Image'
        run: docker build . -t clbo/myapp:${{ github.sha }}

      - name: 'Push Docker Image'
        run: docker push clbo/myapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 'Set up Node.js 20'
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Install SSH Key'
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: 'Deploy to Azure VM'
        env:
          DOCKER_HUB_IMAGE: clbo/myapp:${{ github.sha }}
          VM_USERNAME: azureuser
          VM_PUBLIC_IP: 52.169.211.207
        run: |
          ssh -o StrictHostKeyChecking=no $VM_USERNAME@$VM_PUBLIC_IP << 'EOF'
            docker pull $DOCKER_HUB_IMAGE
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp -p 80:80 $DOCKER_HUB_IMAGE
          EOF
