# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - clbowebservicetest

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_666b31fb02a84a79aad2597887445b99 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_166a4e014861425091e929b246afeff2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_666b31fb02a84a79aad2597887445b99 }}/clbo/flask_deploy_test:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'clbowebservicetest'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_609ef03410f94619845b4e6a87c40067 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_666b31fb02a84a79aad2597887445b99 }}/clbo/flask_deploy_test:${{ github.sha }}'